version: 1.63.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: $(appveyor_repo_commit)
before_build:
  - cmd: git submodule update --init --recursive
  - cmd: dotnet --version
  - cmd: dotnet restore OverwatchToolchain.sln --verbosity m
build_script:
  - cmd: dotnet publish --configuration Release -r win7-x64 --self-contained false -o dist/Release
  - cmd: dotnet publish --configuration Debug -r win7-x64 --self-contained false -o dist/Debug
branches:
  only:
    - master
artifacts:
  - path: dist/Release
    name: toolchain-release
  - path: dist/Debug
    name: toolchain-debug
deploy: false
