version: 1.19.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: $(appveyor_repo_commit)
before_build:
- ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200  api.nuget.org")'
- cmd: >-
    git submodule update --init --recursive

    nuget restore OverwatchToolchain.sln
build:
  project: OverwatchToolchain.sln
  verbosity: minimal
before_package:
- cmd: >-
    del /F /Q dist\Release\*.pdb

    del /F /Q dist\Release\*.xml

    del /F /Q CASCExplorer\CASCExplorer\bin\Release\*.pdb

    del /F /Q CASCExplorer\CASCExplorer\bin\Release\*.xml

    del /F /Q CASCExplorer\CASCConsole\bin\Release\*.pdb

    del /F /Q CASCExplorer\CASCConsole\bin\Release\*.xml
artifacts:
- path: dist/Release
  name: toolchain-release
- path: dist/Release/CascLib.dll
  name: CascLib
- path: dist/Release/OWLib.dll
  name: OWLib
- path: dist/Release/OWReplayLib.dll
  name: OWReplayLib
- path: CASCExplorer/CASCExplorer/bin/Release
  name: CASCExplorer
- path: CASCExplorer/CASCConsole/bin/Release
  name: CASCConsole
cache:
  - packages -> **\packages.config 
